[package]
name = "gibi"
version = "0.1.0"
edition = "2021"
authors = ["Rudolph Almeida <rudolf1.almeida@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
