[package]
name = "gibi"
version = "0.1.0"
edition = "2021"
authors = ["Rudolph Almeida <rudolf1.almeida@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.12", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.17"
