[package]
name = "gibi"
version = "0.1.0"
edition = "2021"
authors = ["Rudolph Almeida <rudolf1.almeida@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
env_logger = "0.10.0"
imgui = "0.11.0"
log = "0.4.17"
paste = "1.0.7"
sdl2 = "0.35.2"
spin_sleep = "1.1.1"
